dist: xenial
language: php
php:
  - '5.6'

jobs:
  include:
    - language: python
      python: 3.8
      install:
      - pip install -r requirements.txt
      script:
      - pytest flask-stuff/test1.py

    - language: node_js
      node_js: 12
      before_script:
      - cd react-stuff/
      install:
      - npm install
      - npm install axios
      - npm install react-beautiful-dnd
      script:
      - CI=false npm run build
