
#dist: xenial
#language: php
#php:
#  - '5.6'
  

language: python
python:
#  - "2.7"
# - "3.4"
# - "3.5"
  - "3.6"      # current default Python on Travis CI
# - "3.7"
# - "3.8"
# - "3.8-dev"  # 3.8 development branch
# - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests

jobs:
  include:
    - language: python
      python: 3.8
      script:
      - python -c "print('Hi from Python!')"
      -pytest flask-stuff/test1.py

   - language: node_js
     node_js: 12
      script:
      - node -e "console.log('Hi from NodeJS!')"

#script:
# - pytest flask-stuff/test1.py

